# Generated by Django 4.1.2 on 2022-10-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="")),
            ],
        ),
    ]
